workflows:
  android:
    name: Build and Distribute APK
    max_build_duration: 60
    environment:
      vars:
        GRADLEW_PATH: "./gradlew"
      android:
        image: "codemagic/android:latest"
    scripts:
      - name: Install dependencies
        script: |
          chmod +x $GRADLEW_PATH
          $GRADLEW_PATH dependencies
      - name: Build APK
        script: |
          $GRADLEW_PATH assembleDebug
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "rahulbolia91@gmail.com"
