workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "dev.yum.myapplication"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rahulbolia91@gmail.com
        notify:
          success: true
